# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt install ffmpeg git -y
          sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
          sudo chmod a+rx /usr/local/bin/youtube-dl
          youtube-dl https://www.youtube.com/watch?v=YImASs5vdE4 -o live
          git clone https://github.com/McDull-GitHub/live
          echo 
          echo ready
          echo
          ffmpeg -i live.mkv
          
      - name: Go Live
        run: ffmpeg -re -i live.mkv -c:v libx264 -preset veryfast -b:v 8000k\
          -bufsize 16000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 1024k -ac 2 \
          -ar 44100 -f flv rtmp://a.rtmp.youtube.com/live2/${{ secrets.CODE }}
#        run: bash live/live live.mkv ${{ secrets.CODE }}
#        run: |
#          ffmpeg -i live.mkv  -c:v libx264 -preset ultrafast -b:v 8000k -bufsize 16000k \
#          -vf "scale=1920:-1,format=yuv420p" -g 50 -c:a aac -b:a 1024k -ac 2 -ar 44100 live.flv
#          ffmpeg -re -i live.flv -c copy -f flv rtmp://a.rtmp.youtube.com/live2/${{ secrets.CODE }}
